name: vdom_benchmark
description: A sample web application
dependencies:
  browser: any
  charted: any
  vdom:
    git: git://github.com/localvoid/vdom.git
  liquid:
    git: git://github.com/localvoid/liquid.git
transformers:
- $dart2js:
    checked: false
    minify: true
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']